repos:
- hooks:
  - entry: /home/nexis/vgws/.venv/bin/python3.6 .selid-hooks/check-identity
    id: select-identity+check-identity
    language: system
    name: Select Identity - check-identity
    require_serial: true
  repo: local
