###
# Bans controls.
###
core.whenReady ->
  $('.jobs').tagit
    fieldName: 'jobs[]'
    availableTags: window.AUTOCOMPLETE_JOBS

  $('button#getlast').click ->
    $.post window.API_FIND_CID, { ckey: $('#banCKey').val() }, (data, status) ->
      #alert("Returned: "+status);
      if status == 'success'
        rows = data.split('\\n')
        $('#banIP').val rows[0]
        $('#banCID').val rows[1]
      else
        alert 'Couldn\'t find that ckey.'
      return
    return
  return

# ---
# generated by js2coffee 2.2.0
